kind: Deployment
apiVersion: apps/v1
metadata:
  name: echo-app
  labels:
    app: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo-app
          image: 'kicbase/echo-server:1.0'
          resources:
            requests:
              memory: "20Mi"    # Request memory
            limits:
              memory: "80Mi"    # Limit memory
