version: '3.8'

services:
  web:
    build:
      context: ./node-postgres-todo/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # NOTE: this is for demo purpose only, in real world, 
      # user/pass, etc. should be via dotenv for reusability + security
      - DATABASE_URL=postgres://postgres:password@db:5432/todo
    depends_on:
      - db

  db:
    image: postgres:13.16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      # init db schema
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: {}
